### ISSUE TITLE
File menu should be first

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#12]
In my opinion, it's not very usable to change something that is standard in every other GUI existing today.

**Comment by centaurialpha** [comment]
You think is wrong ? I copied the idea GUI Telegram :P. Maybe I should be on the Edit menu.

**Comment by ltworf** [comment]
I believe it is a bad idea. I don't want to have to learn a GUI. I want it to work like everything else, so I can use it as fast as possible.
