### ISSUE TITLE
Can't load new relation with same name

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#16]
If I try to load a new relation with the same name as one that already exists, my action is ignored with no error.

**Comment by centaurialpha** [comment]
I do not understand, the right thing would not charge a relation with the same name, right? And that's what we do.

Sorry for my English.

**Comment by ltworf** [comment]
Your English is fine! :P

Well I had this relation loaded, forgot it was loaded, and loaded another one with the same name. Then made a query and the results were unexpected (because I was actually using the old relation).

So it should show an error or possibly inform me of the name collision and show an input dialog where I can chose a different name.
