### ISSUE TITLE
pdb files are not escaped

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#17]
I have created a relation like this

```
name,id
@turi,0
#turi,1
!turi,2
```

Loading this within a database, saving the database and re-loading the database breaks it.

**Comment by centaurialpha** [comment]
Yes, I think you should first check the syntax. Thanks!

**Comment by ltworf** [comment]
You could just use the pickle module and let it serialize automatically.

**Comment by centaurialpha** [comment]
I have not used the module before, I'll look.
