### ISSUE TITLE
Empty intersection is incorrect

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#20]
Intersection of 2 disjoint relations should return an empty relation.

The code does this:
```
        content = self.content.intersection(other_relation.content)

        if not content:
            return new_relation

        for i in content:
            new_relation.insert(i)
```

So if the result is empty it will instead return the 1st relation.

**Comment by ltworf** [comment]
Sorry I misunderstood the code.

**Comment by centaurialpha** [comment]
No problem :) Thanks for helping, I abandoned the project a little for reason of study.
Again, sorry for my English :p

**Comment by ltworf** [comment]
Then you should probably put a note in the README to say that it is abandoned…

**Comment by centaurialpha** [comment]
I'm back :). I would appreciate if you continue to report bugs and pull request ;)
