### ISSUE TITLE
Implement division

### ISSUE THREAD

**Issue by allentiak** [centaurialpha/pireal#34]
Maybe this other project might be useful for you:
https://github.com/ltworf/relational/blob/master/relational/relation.py

**Comment by usercz** [comment]
Division is already present https://github.com/centaurialpha/pireal/blob/master/src/core/relation.py#L206

Keep in mind that this project basically started as a fork of relational with a different UI.

Only recently it got a reimplemented parser.

**Comment by centaurialpha** [comment]
@allentiak The idea is that students implement the division operation in terms of the fundamental relational algebra operators.

@usercz That's right, I initially based on the "relational" project but I had to redo the interpreter to support the relational algebra syntax.
