### ISSUE TITLE
Esto es una nueva issue

### ISSUE THREAD

**Issue by adrianmarello** [centaurialpha/pireal#50]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.

**Comment by debianitram** [comment]
Pibe, era comentar en la anterior ...

**Comment by centaurialpha** [comment]
Ma esa colgada
