### ISSUE TITLE
Correctly attribute copyright

### ISSUE THREAD

**Issue by ltworf** [centaurialpha/pireal#53]
Hello,

Since some of this code is copy-pasted and then the variables are renamed from Relational (https://github.com/ltworf/relational), every file that was done in this fashion must include the original copyright note, and then add the authors who did the further modifications that happened since then.

See for example commit `d333e21bf6dca63153a116b1634e5d7ec6bb9fcc` where some of the variables haven't been renamed.

**Comment by centaurialpha** [comment]
Hi! 

Currently the module [relation.py](https://github.com/centaurialpha/pireal/blob/master/src/core/relation.py) is the only one based on [Relational](https://github.com/ltworf/relational), anyway I have added the line in the copyright :) Sorry for my mistake.

**Comment by ltworf** [comment]
Thanks
